import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

type Language = 'en' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, defaultValue?: string) => string;
  isTranslating: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'app.name': 'SwachhPath',
    'nav.user': 'User Panel',
    'nav.admin': 'Admin Dashboard',
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'theme.contrast': 'High Contrast',
    'font.normal': 'Normal Text',
    'font.large': 'Large Text',
    'user.nearby': 'Nearby Bins',
    'user.route': 'Get Route',
    'user.voice': 'Voice Assistant',
    'user.voice.listening': 'Listening...',
    'user.voice.tap': 'Tap to speak (e.g., "Find nearest bin")',
    'user.youAreHere': 'You are here',
    'user.mcdDept': 'Municipal Corporation of Delhi',
    'user.binId': 'ID',
    'user.findingRoute': 'Finding best route...',
    'user.findNearest': 'Find Nearest Bin',
    'bin.wet': 'Wet Waste',
    'bin.dry': 'Dry Waste',
    'bin.metal': 'Metal Waste',
    'bin.full': 'Full',
    'landing.welcome': 'Welcome to ',
    'landing.tagline': 'The next-generation smart waste management system for Delhi. Powered by IoT, real-time analytics, and AI to keep our city clean and green.',
    'landing.findBins': 'Find Dustbins',
    'landing.adminDash': 'Admin Dashboard',
    'landing.smartDelhi': 'Smart Delhi Initiative',
    'landing.realTimeTracking': 'Real-time waste tracking across the capital.',
    'landing.routeOptimized': 'Route Optimized',
    'landing.saveKm': 'Save 2.4 km today',
    'landing.binFull': 'Bin #089 Full',
    'landing.chandniChowk': 'Chandni Chowk',
    'landing.howItWorks': 'Navigate to Dustbins Easily',
    'landing.howItWorksDesc': 'Finding a clean, available dustbin is now just a tap away. Follow these simple steps to dispose of your waste responsibly.',
    'landing.step1Title': '1. Locate Nearby Bins',
    'landing.step1Desc': 'Open the interactive map to instantly see all smart dustbins around you in Delhi. Color-coded markers show fill levels at a glance.',
    'landing.step2Title': '2. Check Live Status',
    'landing.step2Desc': 'Tap on any bin to see real-time data: wet/dry capacity, metal detection status, and last cleared time. Never walk to a full bin again.',
    'landing.step3Title': '3. Get Directions',
    'landing.step3Desc': 'Click \'Navigate\' to get the shortest walking or driving route directly to the bin. Our system optimizes paths to save you time.',
    'landing.advancedFeatures': 'Advanced Features',
    'landing.iotIntegration': 'IoT Integration',
    'landing.iotDesc': 'Smart dustbins equipped with ESP32, ultrasonic fill-level sensors, and inductive metal detectors for automated sorting.',
    'landing.realTimeAnalytics': 'Real-time Analytics',
    'landing.analyticsDesc': 'Live monitoring of waste levels, usage patterns, and hardware status via Firebase Realtime Database.',
    'landing.routeOptimization': 'Route Optimization',
    'landing.routeDesc': 'Smart algorithms calculate the shortest collection routes for garbage trucks based on bins exceeding 80% capacity.',
    'landing.getInTouch': 'Get in Touch',
    'landing.contactDesc': 'Have questions about SwachhPath or want to report an issue with a dustbin? We\'re here to help keep Delhi clean.',
    'landing.address': 'Address',
    'landing.phone': 'Phone',
    'landing.email': 'Email',
    'landing.sendMessage': 'Send us a Message',
    'landing.firstName': 'First Name',
    'landing.lastName': 'Last Name',
    'landing.emailAddress': 'Email Address',
    'landing.message': 'Message',
    'landing.sendBtn': 'Send Message',
    'profile.title': 'User Profile',
    'profile.edit': 'Edit Profile',
    'profile.save': 'Save Changes',
    'profile.name': 'Full Name',
    'profile.email': 'Email Address',
    'profile.phone': 'Phone Number',
    'profile.address': 'Address',
    'profile.bio': 'Bio / Notes',
    'profile.accountType': 'Account',
    'auth.adminPortal': 'Admin Portal',
    'auth.userLogin': 'User Login',
    'auth.createAccount': 'Create Account',
    'auth.secureAccess': 'Secure access for city administrators',
    'auth.accessSmartBins': 'Access smart dustbin locations and routes',
    'auth.fullName': 'Full Name',
    'auth.emailAddress': 'Email Address',
    'auth.password': 'Password',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.alreadyHaveAccount': 'Already have an account? Sign in',
    'auth.needAccount': 'Need an account? Sign up',
    'auth.backToUserLogin': 'Back to User Login',
    'auth.adminLogin': 'Admin Login',
    'admin.overview': 'Overview',
    'admin.bins': 'All Bins',
    'admin.alerts': 'Alerts',
    'admin.hardware': 'Hardware & Logs',
    'admin.route': 'Route Optimization',
    'admin.totalUsage': 'Total System Usage',
    'admin.criticalBins': 'Critical Bins (>80%)',
    'admin.offlineDevices': 'Offline Devices',
    'admin.weeklyTrends': 'Weekly Usage Trends',
    'admin.fillLevels': 'Current Fill Levels by Location',
    'admin.idLocation': 'ID / Location',
    'admin.status': 'Status',
    'admin.network': 'Network',
    'admin.wetPercent': 'Wet %',
    'admin.dryPercent': 'Dry %',
    'admin.usage': 'Usage',
    'admin.hardwareArch': 'ESP32 System Architecture',
    'admin.apiPayload': 'API Payload Format',
    'admin.apiDesc': 'ESP32 sends data to Firebase via REST API using the following JSON structure:',
    'admin.limitations': 'Known Limitations',
    'admin.limit1': 'Ultrasonic sensors affected by heavy rain/dust.',
    'admin.limit2': 'IR sensor prone to false triggers in direct sunlight.',
    'admin.limit3': 'GPS signal weak indoors or under heavy canopy.',
    'admin.limit4': 'WiFi dependency requires robust municipal network.',
    'admin.optimizedRoute': 'Optimized Collection Route',
    'admin.routeDesc': 'Based on current fill levels (>80%), the following route is recommended for the garbage collection truck.',
    'admin.returnDepot': 'Return to Depot',
    'admin.collect': 'Collect',
    'admin.waste': 'Waste',
    'admin.mcdRoute': 'Route to Nearest MCD HQ',
    'admin.usageInsight': 'Usage Frequency',
    'admin.highUsage': 'High Frequency',
    'admin.mediumUsage': 'Medium Frequency',
    'admin.lowUsage': 'Low Frequency',
    'admin.mlInsight': 'ML Prediction',
    'admin.predictedPeak': 'Predicted Peak',
    'admin.usageHistory': 'Usage History (7d)',
    'admin.confidence': 'Confidence',
    'admin.api': 'API Configuration',
    'admin.apiConfig': 'ThingSpeak API Configuration',
    'bin.usageCount': 'Usage Count',
    'bin.dryCount': 'Dry Count',
    'bin.wetCount': 'Wet Count',
    'bin.distance': 'Distance',
    'bin.latitude': 'Latitude',
    'bin.longitude': 'Longitude',
    'bin.dryFilledLevel': 'Dry Filled Level',
    'bin.wetFilledLevel': 'Wet Filled Level',
    'user.nearbyBins': 'Nearby Bins',
    'user.selectBin': 'Select a bin on the map to view real-time status',
    'user.openDry': 'Open Dry',
    'user.openWet': 'Open Wet',
    'user.routeInfo': 'Route Info',
    'user.kmAway': 'km away',
    'status.online': 'Online',
    'status.offline': 'Offline',
  },
  hi: {
    'app.name': 'स्वच्छपथ',
    'nav.user': 'उपयोगकर्ता पैनल',
    'nav.admin': 'एडमिन डैशबोर्ड',
    'theme.light': 'लाइट',
    'theme.dark': 'डार्क',
    'theme.contrast': 'हाई कंट्रास्ट',
    'font.normal': 'सामान्य टेक्स्ट',
    'font.large': 'बड़ा टेक्स्ट',
    'user.nearby': 'पास के डस्टबिन',
    'user.route': 'रास्ता खोजें',
    'user.voice': 'वॉइस असिस्टेंट',
    'user.voice.listening': 'सुन रहा हूँ...',
    'user.voice.tap': 'बोलने के लिए टैप करें (जैसे, "पास वाला डस्टबिन खोजें")',
    'user.youAreHere': 'आप यहाँ हैं',
    'user.mcdDept': 'दिल्ली नगर निगम',
    'user.binId': 'आईडी',
    'user.findingRoute': 'सबसे अच्छा रास्ता खोज रहे हैं...',
    'user.findNearest': 'पास वाला डस्टबिन खोजें',
    'bin.wet': 'गीला कचरा',
    'bin.dry': 'सूखा कचरा',
    'bin.metal': 'धातु कचरा',
    'bin.full': 'भरा हुआ',
    'landing.welcome': 'स्वागत है ',
    'landing.tagline': 'दिल्ली के लिए अगली पीढ़ी की स्मार्ट कचरा प्रबंधन प्रणाली। हमारे शहर को स्वच्छ और हरा-भरा रखने के लिए IoT, रीयल-टाइम एनालिटिक्स और AI द्वारा संचालित।',
    'landing.findBins': 'डस्टबिन खोजें',
    'landing.adminDash': 'एडमिन डैशबोर्ड',
    'landing.smartDelhi': 'स्मार्ट दिल्ली पहल',
    'landing.realTimeTracking': 'राजधानी में रीयल-टाइम कचरा ट्रैकिंग।',
    'landing.routeOptimized': 'रास्ता अनुकूलित',
    'landing.saveKm': 'आज 2.4 किमी बचाएं',
    'landing.binFull': 'बिन #089 भरा है',
    'landing.chandniChowk': 'चांदनी चौक',
    'landing.howItWorks': 'डस्टबिन तक आसानी से पहुँचें',
    'landing.howItWorksDesc': 'साफ और उपलब्ध डस्टबिन खोजना अब बस एक टैप दूर है। जिम्मेदारी से अपना कचरा फेंकने के लिए इन सरल चरणों का पालन करें।',
    'landing.step1Title': '1. पास के डस्टबिन खोजें',
    'landing.step1Desc': 'दिल्ली में अपने आस-पास के सभी स्मार्ट डस्टबिन को तुरंत देखने के लिए इंटरैक्टिव मानचित्र खोलें। रंग-कोडित मार्कर एक नज़र में भराव स्तर दिखाते हैं।',
    'landing.step2Title': '2. लाइव स्थिति जांचें',
    'landing.step2Desc': 'रीयल-टाइम डेटा देखने के लिए किसी भी बिन पर टैप करें: गीला/सूखा क्षमता, धातु पहचान स्थिति और अंतिम बार साफ किए जाने का समय। कभी भी भरे हुए बिन तक न चलें।',
    'landing.step3Title': '3. दिशा-निर्देश प्राप्त करें',
    'landing.step3Desc': 'सीधे बिन तक सबसे छोटा पैदल या ड्राइविंग रास्ता प्राप्त करने के लिए \'नेविगेट\' पर क्लिक करें। हमारा सिस्टम आपका समय बचाने के लिए रास्तों को अनुकूलित करता है।',
    'landing.advancedFeatures': 'उन्नत सुविधाएँ',
    'landing.iotIntegration': 'IoT एकीकरण',
    'landing.iotDesc': 'स्वचालित छंटाई के लिए ESP32, अल्ट्रासोनिक फिल-लेवल सेंसर और इंडक्टिव मेटल डिटेक्टरों से लैस स्मार्ट डस्टबिन।',
    'landing.realTimeAnalytics': 'रीयल-टाइम एनालिटिक्स',
    'landing.analyticsDesc': 'फायरबेस रीयलटाइम डेटाबेस के माध्यम से कचरे के स्तर, उपयोग के पैटर्न और हार्डवेयर स्थिति की लाइव निगरानी।',
    'landing.routeOptimization': 'मार्ग अनुकूलन',
    'landing.routeDesc': 'स्मार्ट एल्गोरिदम 80% से अधिक क्षमता वाले डस्टबिन के आधार पर कचरा ट्रकों के लिए सबसे छोटे संग्रह मार्गों की गणना करते हैं।',
    'landing.getInTouch': 'संपर्क करें',
    'landing.contactDesc': 'स्वच्छपथ के बारे में प्रश्न हैं या डस्टबिन के साथ किसी समस्या की रिपोर्ट करना चाहते हैं? हम दिल्ली को स्वच्छ रखने में मदद करने के लिए यहाँ हैं।',
    'landing.address': 'पता',
    'landing.phone': 'फोन',
    'landing.email': 'ईमेल',
    'landing.sendMessage': 'हमें संदेश भेजें',
    'landing.firstName': 'पहला नाम',
    'landing.lastName': 'अंतिम नाम',
    'landing.emailAddress': 'ईमेल पता',
    'landing.message': 'संदेश',
    'landing.sendBtn': 'संदेश भेजें',
    'profile.title': 'उपयोगकर्ता प्रोफ़ाइल',
    'profile.edit': 'प्रोफ़ाइल संपादित करें',
    'profile.save': 'परिवर्तन सहेजें',
    'profile.name': 'पूरा नाम',
    'profile.email': 'ईमेल पता',
    'profile.phone': 'फोन नंबर',
    'profile.address': 'पता',
    'profile.bio': 'बायो / नोट्स',
    'profile.accountType': 'खाता',
    'auth.adminPortal': 'एडमिन पोर्टल',
    'auth.userLogin': 'उपयोगकर्ता लॉगिन',
    'auth.createAccount': 'खाता बनाएँ',
    'auth.secureAccess': 'शहर के प्रशासकों के लिए सुरक्षित पहुँच',
    'auth.accessSmartBins': 'स्मार्ट डस्टबिन स्थानों और मार्गों तक पहुँचें',
    'auth.fullName': 'पूरा नाम',
    'auth.emailAddress': 'ईमेल पता',
    'auth.password': 'पासवर्ड',
    'auth.signIn': 'साइन इन करें',
    'auth.signUp': 'साइन अप करें',
    'auth.alreadyHaveAccount': 'पहले से ही एक खाता है? साइन इन करें',
    'auth.needAccount': 'खाता चाहिए? साइन अप करें',
    'auth.backToUserLogin': 'उपयोगकर्ता लॉगिन पर वापस जाएं',
    'auth.adminLogin': 'एडमिन लॉगिन',
    'admin.overview': 'अवलोकन',
    'admin.bins': 'सभी बिन',
    'admin.alerts': 'अलर्ट',
    'admin.hardware': 'हार्डवेयर और लॉग',
    'admin.route': 'मार्ग अनुकूलन',
    'admin.totalUsage': 'कुल सिस्टम उपयोग',
    'admin.criticalBins': 'क्रिटिकल बिन (>80%)',
    'admin.offlineDevices': 'ऑफ़लाइन डिवाइस',
    'admin.weeklyTrends': 'साप्ताहिक उपयोग रुझान',
    'admin.fillLevels': 'स्थान के अनुसार वर्तमान भराव स्तर',
    'admin.idLocation': 'आईडी / स्थान',
    'admin.status': 'स्थिति',
    'admin.network': 'नेटवर्क',
    'admin.wetPercent': 'गीला %',
    'admin.dryPercent': 'सूखा %',
    'admin.usage': 'उपयोग',
    'admin.hardwareArch': 'ESP32 सिस्टम आर्किटेक्चर',
    'admin.apiPayload': 'API पेलोड प्रारूप',
    'admin.apiDesc': 'ESP32 निम्नलिखित JSON संरचना का उपयोग करके REST API के माध्यम से फायरबेस को डेटा भेजता है:',
    'admin.limitations': 'ज्ञात सीमाएं',
    'admin.limit1': 'भारी बारिश/धूल से प्रभावित अल्ट्रासोनिक सेंसर।',
    'admin.limit2': 'सीधी धूप में गलत ट्रिगर होने की संभावना वाला IR सेंसर।',
    'admin.limit3': 'घर के अंदर या भारी छतरी के नीचे GPS सिग्नल कमजोर।',
    'admin.limit4': 'WiFi निर्भरता के लिए मजबूत नगरपालिका नेटवर्क की आवश्यकता है।',
    'admin.optimizedRoute': 'अनुकूलित संग्रह मार्ग',
    'admin.routeDesc': 'वर्तमान भराव स्तर (>80%) के आधार पर, कचरा संग्रह ट्रक के लिए निम्नलिखित मार्ग की सिफारिश की जाती है।',
    'admin.returnDepot': 'डिपो पर वापस जाएं',
    'admin.collect': 'संग्रह करें',
    'admin.waste': 'कचरा',
    'admin.mcdRoute': 'निकटतम MCD मुख्यालय का मार्ग',
    'admin.usageInsight': 'उपयोग आवृत्ति',
    'admin.highUsage': 'उच्च आवृत्ति',
    'admin.mediumUsage': 'मध्यम आवृत्ति',
    'admin.lowUsage': 'कम आवृत्ति',
    'admin.mlInsight': 'ML भविष्यवाणी',
    'admin.predictedPeak': 'अनुमानित पीक',
    'admin.usageHistory': 'उपयोग इतिहास (7 दिन)',
    'admin.confidence': 'आत्मविश्वास',
    'admin.api': 'API कॉन्फ़िगरेशन',
    'admin.apiConfig': 'ThingSpeak API कॉन्फ़िगरेशन',
    'bin.usageCount': 'उपयोग गणना',
    'bin.dryCount': 'सूखी गणना',
    'bin.wetCount': 'गीली गणना',
    'bin.distance': 'दूरी',
    'bin.latitude': 'अक्षांश',
    'bin.longitude': 'देशांतर',
    'bin.dryFilledLevel': 'सूखा भराव स्तर',
    'bin.wetFilledLevel': 'गीला भराव स्तर',
    'user.nearbyBins': 'पास के डस्टबिन',
    'user.selectBin': 'रीयल-टाइम स्थिति देखने के लिए मानचित्र पर एक डस्टबिन चुनें',
    'user.openDry': 'सूखा खोलें',
    'user.openWet': 'गीला खोलें',
    'user.routeInfo': 'मार्ग की जानकारी',
    'user.kmAway': 'किमी दूर',
    'status.online': 'ऑनलाइन',
    'status.offline': 'ऑफ़लाइन',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('swachhpath_lang');
    return (saved as Language) || 'en';
  });
  const [isTranslating] = useState(false);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('swachhpath_lang', lang);
  };

  const t = useCallback((key: string, defaultValue?: string) => {
    if (translations[language] && translations[language][key]) {
      return translations[language][key];
    }
    
    if (language === 'hi' && translations.en[key]) {
      return translations.en[key];
    }

    return defaultValue || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isTranslating }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
